# Generated by Django 6.0.6 on 2026-06-28 12:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('selected_service', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Inquiry',
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text="Maps to 'title' in frontend", max_length=150)),
                ('client', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='e.g. E-commerce Platform, SaaS Dashboard', max_length=100)),
                ('description', models.TextField(help_text="Maps to 'result' in frontend")),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('image_path', models.CharField(blank=True, help_text='Local path fallback e.g. /assets/portfolio/northpeak.png', max_length=255, null=True)),
                ('technologies', models.CharField(help_text='Comma-separated values e.g. Next.js, React, TypeScript', max_length=255)),
                ('live_url', models.URLField(blank=True, null=True)),
                ('case_study_url', models.URLField(blank=True, null=True)),
                ('metric', models.CharField(help_text='e.g. 3.1x or 4B', max_length=50)),
                ('metric_label', models.CharField(help_text='e.g. Conversion or Events/day', max_length=100)),
                ('palette', models.CharField(default='from-spark-primary to-spark-primary-deep', help_text='Tailwind gradient classes', max_length=100)),
                ('size', models.CharField(choices=[('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large')], default='md', max_length=10)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['project_title'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.TextField(help_text="Maps to 'desc' in the frontend card")),
                ('full_description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('image_path', models.CharField(blank=True, help_text='Local path fallback e.g. /assets/services/web-dev.png', max_length=255, null=True)),
                ('bullets', models.CharField(help_text='Comma-separated bullets e.g. Next.js / React, Headless CMS', max_length=255)),
                ('accent', models.CharField(choices=[('primary', 'Primary (Maroon)'), ('gold', 'Gold')], default='primary', max_length=20)),
                ('span', models.BooleanField(default=False, help_text='Span 2 columns in layout')),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Spark Technology', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('logo_path', models.CharField(default='/assets/spark-logo.jpg', max_length=255)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('social_twitter', models.URLField(blank=True, null=True)),
                ('social_linkedin', models.URLField(blank=True, null=True)),
                ('social_dribbble', models.URLField(blank=True, null=True)),
                ('social_github', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text="Maps to 'name' in frontend", max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('message', models.TextField(help_text="Maps to 'quote' in frontend")),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('image_path', models.CharField(blank=True, help_text='Local initials or path fallback e.g. MH', max_length=255, null=True)),
                ('accent', models.CharField(choices=[('primary', 'Primary (Maroon)'), ('gold', 'Gold')], default='primary', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
